# Generated by Django 5.0.6 on 2024-06-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meals_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meals',
        ),
    ]
